const menu = [
  {
    id: 1,
    title: "Clásico",
    category: "Desayuno",
    price: 2800,
    img: "./images/item-1.jpeg",
    desc: "Infusión + medialuna o tortilla + agua o soda",
  },
  {
    id: 2,
    title: "Completo",
    category: "Desayuno",
    price: 5200,
    img: "./images/item-2.jpeg",
    desc: "Infusión + tostadas con queso untable y mermelada + ensalada de frutas + jugo o soda o agua",
  },
  {
    id: 3,
    title: "Saludable",
    category: "Desayuno",
    price: 5800,
    img: "./images/item-3.jpeg",
    desc: "Infusión + tostadas con jamón cocido + mermelada o queso untable + ensalada de frutas + soda.",
  },
  {
    id: 4,
    title: "Bleu XL",
    category: "Desayuno",
    price: 7500,
    img: "./images/item-4.jpeg",
    desc: "Infusión en tazón + 1 medialuna + pan casero con jamón y queso + ensalada de frutas",
  },
  {
    id: 5,
    title: "Torta Rogel",
    category: "Tartas",
    price: 3500,
    img: "./images/item-5.jpeg",
    desc: "Una deliciosa torta de Rogel",
  },
  {
    id: 6,
    title: "Cheesecake",
    category: "Tartas",
    price: 5000,
    img: "./images/item-6.jpeg",
    desc: "Cheesecake clásico con un toque de frescura",
  },
  {
    id: 7,
    title: "Licuado Especial",
    category: "Licuados",
    price: 3000,
    img: "./images/item-7.jpeg",
    desc: "Licuado con ingredientes frescos y de la casa",
  },
  {
    id: 8,
    title: "Café Mediano",
    category: "Cafetería",
    price: 1700,
    img: "./images/item-8.jpeg",
    desc: "Café mediano con opción de leche o solo",
  },
  {
    id: 9,
    title: "Mortadela Gourmet",
    category: "Sandwiches Fríos",
    price: 5400,
    img: "./images/item-9.jpeg",
    desc: "Mortadela, queso, pepino, tomate, y pan casero tostado con manteca",
  },
  {
    id: 10,
    title: "Vegetariano",
    category: "Sandwiches Fríos",
    price: 4200,
    img: "./images/item-10.jpeg",
    desc: "Palta, queso, tomate, huevo y hojas verdes",
  },
];

export default menu;

